[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
  HUGO_VERSION = "0.85.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
 
[context.deploy-preview.environment]
  HUGO_VERSION = "0.85.0"
  
[context.deploy-preview]
  command = "HUGO_BASEURL=$DEPLOY_PRIME_URL hugo --gc --minify"
